In [ ]:
# ## Uždavinys 1

# Naudodami krūties vėžio duomenų rinkinį, prognozuokite, ar navikas yra gerybinis ar piktybinis, 
# naudodami logistinės regresijos modelį su polinominėmis ypatybėmis.

# Duomenų rinkinys: (https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data)


In [10]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

In [5]:
data = pd.read_csv('data.csv', sep=',')

data = data.drop(['Unnamed: 32', 'id'], axis=1)


data['diagnosis'] = data['diagnosis'].apply(lambda x: 1 if x == 'M' else 0)

X = data.drop('diagnosis', axis=1)
y = data['diagnosis']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)
accuracy = accuracy_score(y_pred, y_test)

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)
print(classification_report(y_test, y_pred))

[[85  0]
 [ 4 54]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        85
           1       1.00      0.93      0.96        58

    accuracy                           0.97       143
   macro avg       0.98      0.97      0.97       143
weighted avg       0.97      0.97      0.97       143



In [12]:
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)


log_reg = LogisticRegression(max_iter=10000)
log_reg.fit(X_train_poly, y_train)

y_pred = log_reg.predict(X_test_poly)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{conf_matrix}')

class_report = classification_report(y_test, y_pred)
print(f'Classification Report:\n{class_report}')

Accuracy: 0.9230769230769231
Confusion Matrix:
[[82  5]
 [ 6 50]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.94      0.94        87
           1       0.91      0.89      0.90        56

    accuracy                           0.92       143
   macro avg       0.92      0.92      0.92       143
weighted avg       0.92      0.92      0.92       143



c:\Users\sarun\OneDrive\Documents\Code\Testinei\mokymai\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
# ## Uždavinys 2

# Naudojant širdies ligų duomenų rinkinį, prognozuokite, ar pacientas turi širdies ligą, \
# naudodami logistinės regresijos modelį su polinominėmis ypatybėmis.

# Duomenų rinkinys https://archive.ics.uci.edu/dataset/45/heart+disease

In [42]:
column_names = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','num']
df = pd.read_csv('reprocessed.hungarian.csv', sep=' ', names= column_names)
#sex (1 = male; 0 = female)
# 58 num: diagnosis of heart disease (angiographic disease status)
# -- Value 0: < 50% diameter narrowing
# -- Value 1: > 50% diameter narrowing
# (in any major vessel: attributes 59 through 68 are vessels)


X = df.drop('num', axis=1)
y = df['num']

df.reset_index()

index  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0        0   40    1   2       140   289    0        0      172      0   
1        1   49    0   3       160   180    0        0      156      0   
2        2   37    1   2       130   283    0        1       98      0   
3        3   48    0   4       138   214    0        0      108      1   
4        4   54    1   3       150    -9    0        0      122      0   
..     ...  ...  ...  ..       ...   ...  ...      ...      ...    ...   
289    289   48    0   2        -9   308    0        1       -9     -9   
290    290   36    1   2       120   166    0        0      180      0   
291    291   48    1   3       110   211    0        0      138      0   
292    292   47    0   2       140   257    0        0      135      0   
293    293   53    1   4       130   182    0        0      148      0   

     oldpeak  slope  ca  thal  num  
0        0.0     -9  -9    -9    0  
1        1.0      2  -9    -9    1  
2        0.0     -9  -9    -9    0  
3        1.5      2  -9    -9    3  
4        0.0     -9  -9    -9    0  
..       ...    ...  ..   ...  ...  
289      2.0      1  -9    -9    0  
290      0.0     -9  -9    -9    0  
291      0.0     -9  -9     6    0  
292      1.0      1  -9    -9    0  
293      0.0     -9  -9    -9    0  

[294 rows x 15 columns]

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)


log_reg = LogisticRegression(max_iter=10000)
log_reg.fit(X_train_poly, y_train)


y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)
accuracy = accuracy_score(y_pred, y_test)

conf_matrix = confusion_matrix(y_test, y_pred)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{conf_matrix}')

class_report = classification_report(y_test, y_pred)
print(f'Classification Report:\n{class_report}')

Accuracy: 0.7162162162162162
Confusion Matrix:
[[45  4  0  0  0]
 [ 2  3  0  1  0]
 [ 3  1  0  3  0]
 [ 3  2  0  3  0]
 [ 0  1  1  0  2]]
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.92      0.88        49
           1       0.27      0.50      0.35         6
           2       0.00      0.00      0.00         7
           3       0.43      0.38      0.40         8
           4       1.00      0.50      0.67         4

    accuracy                           0.72        74
   macro avg       0.51      0.46      0.46        74
weighted avg       0.68      0.72      0.69        74



c:\Users\sarun\OneDrive\Documents\Code\Testinei\mokymai\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
