In [ ]:
# ## Uždavinys 1

# Naudodami krūties vėžio duomenų rinkinį, prognozuokite, ar navikas yra gerybinis ar piktybinis, 
# naudodami logistinės regresijos modelį su polinominėmis ypatybėmis.

# Duomenų rinkinys: (https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data)


In [105]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
import warnings
from sklearn.preprocessing import StandardScaler

In [177]:
data = pd.read_csv('data.csv', sep=',')

data = data.drop(['Unnamed: 32', 'id'], axis=1)


data['diagnosis'] = data['diagnosis'].apply(lambda x: 1 if x == 'M' else 0)

X = data.drop('diagnosis', axis=1)
y = data['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y)

skaler = StandardScaler()
X_train = skaler.fit_transform(X_train)
X_test = skaler.transform(X_test)

poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)


log_reg = LogisticRegression(max_iter=10000)
log_reg.fit(X_train_poly, y_train)

y_pred = log_reg.predict(X_test_poly)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{conf_matrix}')

class_report = classification_report(y_test, y_pred)
print(f'Classification Report:\n{class_report}')

# def predict_cancer(x):
#     warnings.filterwarnings("ignore", message="X does not have valid feature names")
#     prediction = model.predict([x])
#     result = 'Piktybinis' if prediction[0] == 1 else 'Gerybinis'
#     print(result); return result

# # predict_cancer(X_test.iloc[1].values)

Accuracy: 0.993006993006993
Confusion Matrix:
[[92  1]
 [ 0 50]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99        93
           1       0.98      1.00      0.99        50

    accuracy                           0.99       143
   macro avg       0.99      0.99      0.99       143
weighted avg       0.99      0.99      0.99       143



In [15]:
# ## Uždavinys 2

# Naudojant širdies ligų duomenų rinkinį, prognozuokite, ar pacientas turi širdies ligą, \
# naudodami logistinės regresijos modelį su polinominėmis ypatybėmis.

# Duomenų rinkinys https://archive.ics.uci.edu/dataset/45/heart+disease

In [259]:
column_names = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','num']
df = pd.read_csv('reprocessed.hungarian.csv', sep=' ', names= column_names)
#sex (1 = male; 0 = female)
# 58 num: diagnosis of heart disease (angiographic disease status)
# -- Value 0: < 50% diameter narrowing
# -- Value 1: > 50% diameter narrowing
# (in any major vessel: attributes 59 through 68 are vessels)


X = df.drop('num', axis=1)
y = df['num']

df.reset_index()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42 )

skaler = StandardScaler()
X_train = skaler.fit_transform(X_train)
X_test = skaler.transform(X_test)

poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)


log_reg = LogisticRegression(max_iter=10000)
log_reg.fit(X_train_poly, y_train)


y_pred = log_reg.predict(X_test_poly)
# y_prob = model.predict_proba(X_test)
accuracy = accuracy_score(y_pred, y_test)

conf_matrix = confusion_matrix(y_test, y_pred)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

conf_matrix = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{conf_matrix}')

class_report = classification_report(y_test, y_pred)
print(f'Classification Report:\n{class_report}')

Accuracy: 0.6271186440677966
Confusion Matrix:
[[35  3  0  0  0]
 [ 5  0  1  1  2]
 [ 0  1  2  1  2]
 [ 4  0  1  0  0]
 [ 0  1  0  0  0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.92      0.85        38
           1       0.00      0.00      0.00         9
           2       0.50      0.33      0.40         6
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         1

    accuracy                           0.63        59
   macro avg       0.26      0.25      0.25        59
weighted avg       0.56      0.63      0.59        59



In [ ]:
# ## Uždavinys 3

# Naudojant Pima Indians Diabetes duomenų rinkinį, prognozuokite, ar pacientas turi diabetą, 
# naudodami logistinės regresijos modelį su polinominėmis ypatybėmis.

# Duomenų rinkinys: Pima Indians Diabetes Database https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database/data

In [ ]:
df = pd.read_csv('diabetes.csv')
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
model1 = LogisticRegression()
model1.fit(X_train, Y_train)
Y_pred = model1.predict(X_test)
print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))
model2 = RandomForestClassifier()
model2.fit(X_train, Y_train)
Y_pred = model2.predict(X_test)
print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))